module.exports = {
  content: ['./src/**/*{html,php,js}'],
  theme: {
    screens: {
      'xl': {'max': '1280px'},
      'lg': {'max': '1024px'},
      'md': {'max': '768px'},
      'sm': {'max': '640px'},
    },
    colors: {
      'black': 'var(--color-black)',
      'white': 'var(--color-white)',
      'primary': 'var(--color-primary)',
    },
    fontFamily: {
      'noto-sans': ['"Noto Sans JP", sans-serif'],
      'roboto': ['"Roboto", sans-serif'],
      'outfit': ['"Outfit", sans-serif'],
    },
    letterSpacing: {
      'xs': '-0.05em',
      'sm': '-0.025em',
      'normal': '0',
      'lg': '0.025em',
      'xl': '0.05em',
      '2xl': '0.075em',
      '3xl': '0.1em',
      '4xl': '0.15em',
      '5xl': '0.2em',
    },
    lineHeight: {
      'none': '1',
      'sm': '1.25',
      'normal': '1.5',
      'lg': '1.75',
      'xl': '2',
      '2xl': '2.5',
    },
    extend: {
      fontSize: {
        '2xs': 'var(--text-2xs)',
        'xs': 'var(--text-xs)',
        'sm': 'var(--text-sm)',
        'base': 'var(--text-base)',
        'lg': 'var(--text-lg)',
        'xl': 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
      },
      spacing: {
        'xs': 'var(--spacing-xs)',
        'sm': 'var(--spacing-sm)',
        'md': 'var(--spacing-md)',
        'lg': 'var(--spacing-lg)',
        'xl': 'var(--spacing-xl)',
        '2xl': 'var(--spacing-2xl)',
        '3xl': 'var(--spacing-3xl)',
        '4xl': 'var(--spacing-4xl)',
        '5xl': 'var(--spacing-5xl)',
        '6xl': 'var(--spacing-6xl)',
        '7xl': 'var(--spacing-7xl)',
        'header': 'var(--spacing-header)',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [
  ],
};